MyFormBuilder/ViewModels/MyFormViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyFormBuilder.ViewModels
{

    public class MyFormSubmissionVM
    {
        public int Id { get; set; }
        public int MyFormId { get; set; }
        public string ApplicationUserID { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public ICollection<FormData> SubmittedData { get; set; }
    }

    public class FormData
    {
        public string name { get; set; }
        public string value { get; set; }
    }

    public class FormDataItems
    {
        public List<FormData> data { get; set; }
    }

    public class ViewFormSubmissionsVM
    {
        public int Id { get; set; } //Form ID
        public string FormName { get; set; }
        public string ApplicationUser { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public ICollection<FormData> SubmittedData { get; set; }
    }

    public class LayoutItems
    {
        public List<LayoutItem> Items { get; set; }
    }

    public class LayoutItem
    {
        public string Name { get; set; }
        public string Label { get; set; }
    }
}

MyFormBuilder/Controllers/MyFormsController.cs
using MyFormBuilder.Models;
using MyFormBuilder.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MyFormBuilder.Controllers
{
    public class MyFormsController : Controller
    {
        private MyFormBuilderModel db = new MyFormBuilderModel();

        // GET: MyForms
        public ActionResult Index()
        {
            return View(db.MyForms.ToList());
        }

        // GET: MyForms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyForm myForm = db.MyForms.Find(id);
            if (myForm == null)
            {
                return HttpNotFound();
            }
            return View(myForm);
        }

        [HttpPost]
        public ActionResult SaveForm(MyFormBuilder.Models.MyForm Model)
        {
            if (Model != null)
            {
                //save the form to the database
                var newForm = new Models.MyForm
                {
                    FormName = Model.FormName,
                    FormLayout = Model.FormLayout,
                    IsActive = Model.IsActive
                };

                db.MyForms.Add(newForm);
                db.SaveChanges();


                return Json("Success");
            }
            else
            {
                return Json("An Error Has occured");
            }
        }

        public ActionResult SubmitForm(MyFormSubmissionVM submission)
        {
            if (ModelState.IsValid)
            {
                var myform = db.MyForms.Find(submission.MyFormId); //find the relevant form

                var submitteddata = JsonConvert.SerializeObject(submission.SubmittedData);               
                

                //now write the submission to the database
                MyFormSubmission submit = new MyFormSubmission
                {
                    ApplicationUserID = "ABCD",
                    DateTimeCreated = DateTime.Now,
                    MyFormId = myform,
                    SubmittedData = submitteddata
                };

                db.MyFormSubmissions.Add(submit);
                db.SaveChanges();

                return Json("Success");
            }
            else
            {
                return Json("We have a problem");
            }
        }

        public ActionResult ViewSubmissions(int ID) //the form id
        {
            //get the submisisons for this form
            var Submissions = db.MyFormSubmissions.Where(s => s.MyFormId.Id == ID).ToList();

            //get the form details
            var Form = db.MyForms.Find(ID);

            //get the form data 
            dynamic FormLayout = JsonConvert.DeserializeObject(Form.FormLayout);

            //store all the required headers in a dictionary object for later
            IDictionary<string, string> fields = new Dictionary<string, string>();
            foreach(var layout in FormLayout)
            {
                if (layout.type.ToString() != "header" && layout.type.ToString() != "paragraph")
                {
                    //an input type
                    fields.Add(layout.name.ToString(), layout.label.ToString());
                }
            }

            //object to store the output
            List<ViewFormSubmissionsVM> displayList = new List<ViewFormSubmissionsVM>();

            
            //loop submissions
            foreach(var submission in Submissions)
            {
                ViewFormSubmissionsVM displayItem = new ViewFormSubmissionsVM 
                {
                    ApplicationUser = submission.ApplicationUserID,
                    DateTimeCreated = submission.DateTimeCreated,
                    FormName = Form.FormName,
                    Id = submission.Id,
                };

                //now we have to convert the data
                dynamic des = JsonConvert.DeserializeObject(submission.SubmittedData);

                List<FormData> formDatas = new List<FormData>();

                //loop each data item (field)
                foreach(var de in des) {
                    if (fields.TryGetValue(de.name.ToString(), out string result))
                    {
                        //continue       
                    }
                    else
                    {
                        //can't find a matching field - use the field name
                        result = de.name.ToString();
                    }
                    //add the new field with the submitted data
                    formDatas.Add(new FormData
                    {
                        name = result, //
                        value = de.value.ToString()
                    });
                }
                //add the form datas
                displayItem.SubmittedData = formDatas;

                displayList.Add(displayItem);
            }

            //pass field list 
            ViewBag.FieldList = fields;

            //form name for display purposes
            ViewBag.FormName = Form.FormName;
            //now we have to loop all of the 
            return View(displayList);

        }

        // GET: MyForms/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MyForms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FormName,FormLayout,IsActive")] MyForm myForm)
        {
            if (ModelState.IsValid)
            {
                db.MyForms.Add(myForm);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(myForm);
        }

        // GET: MyForms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyForm myForm = db.MyForms.Find(id);
            if (myForm == null)
            {
                return HttpNotFound();
            }
            return View(myForm);
        }

        // POST: MyForms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FormName,FormLayout,IsActive")] MyForm myForm)
        {
            if (ModelState.IsValid)
            {
                db.Entry(myForm).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(myForm);
        }

        // GET: MyForms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MyForm myForm = db.MyForms.Find(id);
            if (myForm == null)
            {
                return HttpNotFound();
            }
            return View(myForm);
        }

        // POST: MyForms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MyForm myForm = db.MyForms.Find(id);
            db.MyForms.Remove(myForm);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyFormBuilder/Views/MyForms/Create.cshtml
@{
    ViewBag.Title = "Home Page";
}
<script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>

@Scripts.Render("~/bundles/FormBuilderJS")

<div class="row">
    <div class="col-md-12">
        <h3>Create a New Form</h3>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h5>Please enter a name for this form</h5>
        <input type="text" id="txtformName" />
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div id="build-wrap"></div>
    </div>
</div>

MyFormBuilder/Views/MyForms/Delete.cshtml
@model MyFormBuilder.Models.MyForm

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MyForm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FormName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FormName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FormLayout)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FormLayout)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyFormBuilder/Views/MyForms/Details.cshtml
@model MyFormBuilder.Models.MyForm

@{
    ViewBag.Title = "Details";
}

<script src="https://formbuilder.online/assets/js/form-render.min.js"></script>

@Scripts.Render("~/bundles/FormRenderJS")



<h2>Please complete @Model.FormName</h2>

@Html.HiddenFor(m => m.FormLayout)
@Html.HiddenFor(m => m.Id)

@{Html.BeginForm("SubmitForm", "MyForms", FormMethod.Post, new { @id = "AjaxPostForm" }); }


    @Html.ValidationSummary(true)


    <div class="row">
        <div class="col-md-12">
            <div id="fb-render"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <input type="submit">
        </div>
    </div>

@{ Html.EndForm(); }

MyFormBuilder/Views/MyForms/Edit.cshtml
@model MyFormBuilder.Models.MyForm

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MyForm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FormName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FormName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FormName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FormLayout, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FormLayout, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FormLayout, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyFormBuilder/Views/MyForms/Index.cshtml
@model IEnumerable<MyFormBuilder.Models.MyForm>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FormName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FormLayout)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FormName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FormLayout)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MyFormBuilder/Views/MyForms/ViewSubmissions.cshtml
@model IEnumerable<MyFormBuilder.ViewModels.ViewFormSubmissionsVM>
@{
    ViewBag.Title = "View Submissions";
}

<div class="row">
    <div class="col-md-12">

        <h2>View Submissions for @ViewBag.FormName</h2>

    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped" id="tSubmissions">
            <thead>
                <tr>
                    <th>Submitted By</th>
                    <th>Submission Date</th>
                    @foreach(var field in ViewBag.FieldList)
                    {
                        <th>@field.value</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach(var submit in Model)
                {
                    <tr>
                        <th>@submit.ApplicationUser</th>
                        <th>@submit.DateTimeCreated</th>
                        @foreach(var field in ViewBag.FieldList)
                        {
                            bool found = false;
                            //find the matching item in the model
                            foreach(var detail in submit.SubmittedData)
                            {
                                if(detail.name == field.key)
                                {
                                    <td>@detail.value</td>
                                    found = true;
                                }
                            }
                            if (found == false)
                            {
                                //write out blank if they didn't supply an answer
                                <td>&nbsp;</td>
                            }
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>